spring: 
  kafka: 
    consumer: 
      bootstrap-servers: 68.32.96.148:9092
      group-id: flink3
      enable-auto-commit: true
      auto-commit-interval: 1000
      session-timeout-ms: 6000
    producer: 
      bootstrap-servers: 68.32.96.148:9092
    template: 
      default-topic: park
    
#logging: 
  #config: classpath:logback-boot.xml